### PR TITLE
adding support to run CDEPS as a part of HAFS application

### PR DESCRIPTION
**Pull request by uturuncoglu**
### Description of changes
This PR aims to support CDEPS as a part of HAFS application and including following modifications:
- PIO and genf90 are updated to latest versions. This is required to support CDEPS that requires newer version of PIO. Currently, CDEPS uses PIO installed along with CMEPS under HAFS application
- It makes PIO initialization optional. HAFS application initializes PIO in the NEMS driver because HAFS application has both CMEPS and CDEPS and both of them requires PIO

### Specific notes
Testing with S2S is critical since we change the PIO version and Makefiles under news directory. @DeniseWorthen if you could test it with S2S that would be great.

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers?
 - [x] bit for bit
 - [ ] different at roundoff level
 - [ ] more substantial 

Any User Interface Changes (namelist or namelist defaults changes)?
 - [ ] Yes
 - [x] No

Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required):
- [ ] (required) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [x] (required) CESM testlist_drv.xml
   - machines and compilers: Cheyenne, Intel + MPT
   - details (e.g. failed tests):
```
qcmd -l walltime=4:00:00 -- ./create_test --xml-testlist ../src/drivers/nuopc/cime_config/testdefs/testlist_drv.xml --xml-machine cheyenne --xml-category nuopc --compare oct14 --baseline-root /glade/p/cesmdata/cseg/cmeps_baselines
```
```
    FAIL ERS_Vnuopc_Ld5.f19_f19_mg17.I2000Clm50Sp.cheyenne_intel.clm-default TPUTCOMP Error: Computation time increase > 25 pct from baseline
    FAIL ERS_Vnuopc_Ln9_N3.f19_g17_rx1.A.cheyenne_intel TPUTCOMP Error: Computation time increase > 25 pct from baseline
    FAIL SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel TPUTCOMP Error: Computation time increase > 25 pct from baseline
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io MEMCOMP Error: Memory usage increase > 10% from baseline
```
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-S2S:
- [ ] (required) UFS-S2S testing
   - description:
   - details (e.g. failed tests):

Hashes used for testing:
- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch: nuopc_dev
  - hash:
- [ ] UFS-S2S, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch:
  - hash:

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@mvertens i am testing it with CESM application now. @DeniseWorthen if you could test it with S2S that would be great because I update PIO and build system to support HAFS application.

**Comment by DeniseWorthen** [comment]
For the ufs applications, we've actually taken internal PIO lib build out of cmeps (remove from nems/lib). Instead use what is in the hpc stack. This was part of the move to cmake.

**Comment by uturuncoglu** [comment]
@DeniseWorthen yes, I know but all the UFS models are not synchronized and they are not using the same code base. So, this will allow us to support both PIO configuration is the same time at least for the near future.

**Comment by DeniseWorthen** [comment]
I believe these two lines mediator/Makefile 

https://github.com/ESCOMP/CMEPS/blob/cc634da8ce76cc31122ed0b01984a003275500e4/mediator/Makefile#L61
https://github.com/ESCOMP/CMEPS/blob/cc634da8ce76cc31122ed0b01984a003275500e4/mediator/Makefile#L62

need to have the .F90 replaced by '.o'.

**Comment by uturuncoglu** [comment]
@mvertens @DeniseWorthen could you review this and let me know if there is an issue. I need to merge it with master to continue to work on HAFS CDEPS integration.

**Comment by DeniseWorthen** [comment]
We've removed this as a submodule, so I can merge this and test we can still build and run but it won't be testing the new PIO if that is your concern.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Thanks for your reminder. That is great but i still need this PR to work with HAFS. Once HAFS app also follow the same way with S2S, all PIO related stuff can be removed from the CMEPS.

**Comment by uturuncoglu** [comment]
@mvertens @DeniseWorthen It turns out that this PR gets old and it has problem. I am creating a new branch top of master (feature/hafs_cdeps_fixed) and I am currently testing it and once it passes under HAFS app, I'll close this PR and open a new one, if you don't mind.

**Pull request closed without merging**
