### PR TITLE
Diags optional in configfile

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
If budget variables are not in config file set them to 0 and continue

### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #): #116 

Are changes expected to change answers?
 - [X] bit for bit
 - [ ] different at roundoff level
 - [ ] more substantial 

Any User Interface Changes (namelist or namelist defaults changes)?
 - [ ] Yes
 - [X] No

Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required):
- [X] (required) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines: cheyenne
   - details (e.g. failed tests):  
- [X] (required) CESM testlist_drv.xml
   - machines and compilers: cheyenne intel 
   - details (e.g. failed tests): All pass  oct22 baselines generated
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-S2S:
- [ ] (required) UFS-S2S testing
   - description:
   - details (e.g. failed tests):

Hashes used for testing:
- [X] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch: nuopc_dev
  - hash:9118a884f
- [ ] UFS-S2S, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch:
  - hash:

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
I have a run on cheyenne here:

/glade/scratch/worthen/hour2_fix

which is now failing w/ a different error:

 ESMCI_Attribute_F.C:1888 c_esmc_attpacksetcharlist() Not found  - This Attribute package does not have an Attribute named budget_inst

**Comment by jedwards4b** [comment]
20201023 093659.406 ERROR            PET000 ESMCI_Attribute_F.C:1888 c_esmc_attpacksetcharlist() Not found  - This Attribute package do\
es not have an Attribute named budget_inst                                                                                              
                                                                                                                                        
20201023 093659.406 ERROR            PET000 ESMF_Attribute.F90:28147 ESMF_AttSetChar Operation not yet supported  - Internal subroutine\
 call returned Error                                                                                                                    
20201023 093659.406 ERROR            PET000 src/addon/NUOPC/src/NUOPC_Comp.F90:1494 Operation not yet supported  - Passing error in ret\
urn code                                                                                                                                
20201023 093659.406 ERROR            PET000 med_diag_mod.F90:356 Operation not yet supported  - Passing error in return code           

@DeniseWorthen  Seems ESMF documents something unsupported, I've removed it - please try again.

**Comment by DeniseWorthen** [comment]
It's now failing on the retrieval of the alarm settings for the budgets (same run directory).

**Comment by jedwards4b** [comment]
@DeniseWorthen please try once more.

**Comment by DeniseWorthen** [comment]
OK, that compile and ran. Great. 

Can you fix the mediator/Makefile too before you merge? 

-med_utils_mod.o : med_kind_mod.o med_utils_mod.F90
-med_diag_mod.o : med_kind_mod.o med_time_mod.o med_utils_mod.o med_methods_mod.o med_internalstate_mod.o med_diag_mod.F90
+med_utils_mod.o : med_kind_mod.o
+med_diag_mod.o : med_kind_mod.o med_time_mod.o med_utils_mod.o med_methods_mod.o med_internalstate_mod.o

**Comment by jedwards4b** [comment]
@DeniseWorthen done - thank you for helping to test.

**Comment by DeniseWorthen** [comment]
happy to help.

**Comment by jedwards4b** [comment]
@DeniseWorthen  After consulting with the ESMF team I came up with one hopefully final change - can you give it a try and let me know?  Thanks

**Comment by DeniseWorthen** [comment]
That also works.

**Review by mvertens — APPROVED** [review]

**Pull request merged**
