### PR TITLE
Fix aoflux for UFS

### LINKED ISSUE #448: trouble w/ the gust variables
@jedwards4b I'm having trouble w/ the gust variables again. I've made this change
```
index ad2eda90..1678238d 100644
--- a/mediator/med_phases_aofluxes_mod.F90
+++ b/mediator/med_phases_aofluxes_mod.F90
@@ -1717,10 +1717,6 @@ end subroutine med_aofluxes_map_ogrid2xgrid_input
     call fldbun_getfldptr(fldbun, 'So_duu10n', aoflux_out%duu10n, xgrid=xgrid, rc=rc)
     if (chkerr(rc,__LINE__,u_FILE_u)) return

-    call fldbun_getfldptr(fldbun, 'So_ugustOut', aoflux_out%ugust_out, xgrid=xgrid, rc=rc)
-    if (chkerr(rc,__LINE__,u_FILE_u)) return
-    call fldbun_getfldptr(fldbun, 'So_u10withGust', aoflux_out%u10_withGust, xgrid=xgrid, rc=rc)
-    if (chkerr(rc,__LINE__,u_FILE_u)) return
     call fldbun_getfldptr(fldbun, 'So_u10res', aoflux_out%u10res, xgrid=xgrid, rc=rc)
     if (chkerr(rc,__LINE__,u_FILE_u)) return
     call fldbun_getfldptr(fldbun, 'Faox_taux', aoflux_out%taux, xgrid=xgrid, rc=rc)
@@ -1752,8 +1748,12 @@ end subroutine med_aofluxes_map_ogrid2xgrid_input
     if (add_gusts) then
        call fldbun_getfldptr(fldbun, 'So_ugustOut', aoflux_out%ugust_out, xgrid=xgrid, rc=rc)
        if (chkerr(rc,__LINE__,u_FILE_u)) return
+       call fldbun_getfldptr(fldbun, 'So_u10withGust', aoflux_out%u10_withGust, xgrid=xgrid, rc=rc)
+       if (chkerr(rc,__LINE__,u_FILE_u)) return
+
     else
        allocate(aoflux_out%ugust_out(lsize)); aoflux_out%ugust_out(:) = 0._R8
+       allocate(aoflux_out%u10_withGust(lsize)); aoflux_out%u10_withGust(:) = 0._R8
     end if

   end subroutine set_aoflux_out_pointers
```

Which I think I can fix. It seems the last gust PR created a duplicate line for getting the ``So_ugustOut`` fldptr. But I think putting them both inside the ``use_gusts`` works. 

I'm not sure what to do with the ``So_u10res`` pointer. Is that always used regardless of whether gusts are included or not?

_Originally posted by @DeniseWorthen in https://github.com/ESCOMP/CMEPS/issues/447#issuecomment-2030643694_

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Adds required fields to the ufs FldsExchange and checks for rainc being associated in ``med_phases_aoflux_mod``. 

fixes #448

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@DeniseWorthen I was also discussing these with @jedwards4b and it seems that there are some development in NOAA-EMC side related with this issue that is not pushed to ESCOMP yet. Please see following links,

https://github.com/ESCOMP/CMEPS/blob/3b1e50baab57c739434a4e62937a96a7bea3faf3/mediator/med_phases_aofluxes_mod.F90#L1604

https://github.com/NOAA-EMC/CMEPS/blob/4e19850cb083bc474b7cde5dc2f8506ec74cc442/mediator/med_phases_aofluxes_mod.F90#L1600C1-L1603C14

**Comment by uturuncoglu** [comment]
@DeniseWorthen I think this PR aims to fix those issues and update ESCOMP. Right? I was also looking to this but maybe you already done it. Let me know if you need help.

**Comment by DeniseWorthen** [comment]
@uturuncoglu Moving the rainc inside the ``add_gusts``  was added by you in https://github.com/ESCOMP/CMEPS/commit/64e1c276dee0de636b03a9bd1186fb794699b02d. But at the top of main at ESCOMP, it is no longer under an ``add_gusts`` conditional
https://github.com/ESCOMP/CMEPS/blob/3b1e50baab57c739434a4e62937a96a7bea3faf3/mediator/med_phases_aofluxes_mod.F90#L1602-L1605

**Comment by uturuncoglu** [comment]
@DeniseWorthen Okay. It seems that it is removed with other PR. Right? @jedwards4b Do you know why? Was it creating issue with CESM?

**Comment by uturuncoglu** [comment]
@DeniseWorthen @jedwards4b As I remember we are testing all the PR with CESM.

**Comment by DeniseWorthen** [comment]
@uturuncoglu I was testing Jim's alarm fix branch and found that it failed for UFS, because of the changes in the aoflux that was in main. This may not be the optimal way of fixing aoflux from CESM's perspective, but I can at least run Jim's alarm fix branch if I include these changes.

**Comment by DeniseWorthen** [comment]
@uturuncoglu @jedwards4b I was able to test your PR #447 if I also merged in this fix. All tests passed for UFS. Let me know how you want to proceed---if these changes work for CESM or you need a different fix.

**Comment by DeniseWorthen** [comment]
@jedwards4b I've tested this PR again w/ UFS and it passes all our tests. Thanks.

**Comment by jedwards4b** [comment]
Thank you @DeniseWorthen  I'm not going to be able to get to this until after the CESM meeting next week, but I'll make it a high priority then.

**Comment by DeniseWorthen** [comment]
@jedwards4b I realized there was a much simpler fix for UFS than I initially thought, requiring only a single change in the med_phases_aoflux module. The remaining required changes can go into our UFS fldsExchange.

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
