### PR TITLE
Implementation of glc->ocn coupling via going through mosart 

### PR DESCRIPTION
**Pull request by mvertens**
### Specific notes
- This implements the GLC->OCN coupling by having GLC send the runoff ice and liquid fluxes to MOSART which are then routed directly to the outlet points and then mapped to the ocean using the nearest-neighbor plus smoothing custom files.
- The code to map from GLC->ICE has been removed since there is no current code to implement this at the current time.

Contributors other than yourself, if any: None

CMEPS Issues Fixed: None

Are changes expected to change answers?  Only for fully coupled compsets with active CISM and a greenland ice sheet, otherwise bfb

Any User Interface Changes? The following namelist variables and associated xml variables have been removed
ocn2glc_levels, glc2ocn_liq_rmapname, glc2ocn_ice_rmapname
GLC2ICE_RMAPNAME, GLC2OCN_LIQ_RMAPNAME, GLC2OCN_ICE_RMAPNAME

The following xml variables have been removed from config_component.xml since the only allowed values are idmap or unset which are now set in the namelist_definition_drv.xml file
```xml
  <entry id="ROF2OCN_FMAPNAME">
  <entry id="GLC2ICE_RMAPNAME">
  <entry id="GLC2OCN_LIQ_RMAPNAME">
  <entry id="GLC2OCN_ICE_RMAPNAME">
  <entry id="OCN2WAV_SMAPNAME">
  <entry id="ICE2WAV_SMAPNAME">
  <entry id="WAV2OCN_SMAPNAME">
```

### Testing performed
Using cesm2_3_beta17 checkout with the following changes:
- cmeps
  - branch = feature/cism2mosart
  - repo_url = https://github.com/mvertens/CMEPS.git
- cism 
  - branch = feature/cism2mosart
  - repo_url = https://github.com/mvertens/CISM-wrapper
- mosart
  - branch = feature/cism2mosart
  - repo_url = https://github.com/mvertens/MOSART

Verified that the following was bfb with cesm2_3_beta17 baseline
SMS_Ld2.f09_t232.B1850MOM.derecho_intel.mom-bcompset
Verified that the following had answer changes with cesm2_3_beta17 baselines (as expected)
SMS_Ld5.f09_g17.B1850G.derecho_intel.allactive-cism-test_coupling

Note that the

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Review by jedwards4b — APPROVED** [review]
Looks good - I will work on the github test.

**Comment by slevis-lmwg** [comment]
just noting: 
I think this PR will close #437

**Comment by billsacks** [comment]
@mvertens - I just tried reproducing one of the tests you mentioned above. I got an error at preview_namelists time, saying that `rtmhist_ndens` (which appears in `cime_config/testmods_dirs/allactive/defaultio/user_nl_mosart` in the CESM repository) doesn't exist in MOSART's namelist definition any more. I can simply remove it for the test I'm doing, but is there a fix that should be put into CESM for this?

**Comment by jedwards4b** [comment]
@billsacks Those names have been shortened to just ndens etc (drop the rtmhist_ part) I have it in my cesm sandbox, but haven't commited it yet.

**Comment by jedwards4b** [comment]
@mvertens, @gustavo-marques has some questions/concerns about this PR.  I will send an invitation to meet to discuss on Monday.

**Pull request merged**
