### PR TITLE
Fix CPP ESMF_VERSION_MAJOR and ESMF_VERSION_MINOR definitions.

### PR DESCRIPTION
**Pull request by danrosen25**
### Description of changes
Add CPPDEFS to mediator/Makefile
- ESMF_VERSION_MAJOR
- ESMF_VERSION_MINOR

Check ESMF_VERSION_MAJOR and ESMF_VERSION_MINOR
- mediator/esmFlds.F90
- mediator/med.F90

### Specific notes

Contributors other than yourself, if any:
none

CMEPS Issues Fixed (include github issue #):
use ESMF_Version_* to get version dependent differences in CMEPS #74

It's not a fix to this issue per se but version macros are not automatically passed to the preprocessor unless added to the CPPDEFS in mediator/Makefile. Also the code should check both MAJOR and MINOR versions.

Are changes expected to change answers?
 - [X] bit for bit

Any User Interface Changes (namelist or namelist defaults changes)?
 - [X] No

Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required):
- [ ] (required) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (required) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-S2S:
- [ ] (required) UFS-S2S testing
   - description:
   - details (e.g. failed tests):

Hashes used for testing:
- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch: nuopc_dev
  - hash:
- [ ] UFS-S2S, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch:
  - hash:

### CODE REVIEW

**Comment by danrosen25** [comment]
@jedwards4b @uturuncoglu @mvertens 

Hi All,
I know you're thinking about replacing the CPP based ESMF VERSION checks but in the mean time please look at this fix. Question: How were you previously passing "-DESMF_VERSION_MAJOR=8 -DESMF_VERSION_MINOR=1" to the preprocessor?

Thanks.
Dan Rosen

**Comment by jedwards4b** [comment]
These were provided in esmf.mk and used in the [cime Makefile](https://github.com/ESMCI/cime/blob/master/scripts/Tools/Makefile#L321)

**Review by jedwards4b — APPROVED** [review]

**Comment by danrosen25** [comment]
Thanks @jedwards4b 
Just a note := will overwrite CPPDEFS, were you building with INTERNAL_PIO_INIT defined?

ifdef INTERNAL_PIO_INIT
CPPDEFS := -DINTERNAL_PIO_INIT
endif

**Comment by jedwards4b** [comment]
@danrosen25 I've never used this Makefile and not sure who wrote it, but that looks like a mistake to me.

**Comment by jedwards4b** [comment]
The cime based build doesn't use this Makefile.

**Comment by rsdunlapiv** [comment]
We do need to make sure we preserve the `-DINTERNAL_PIO_INIT` since in UFS this is the only component using PIO, so the it needs to initialize PIO itself.  The line is question is the first definition of CCPDEFS, so shouldn't the `:=` be okay in that case?

**Comment by danrosen25** [comment]
@rsdunlapiv 
Setting the CPPDEFS variable using `:=` is correct if CPPDEFS is only used locally but it will override global CPPDEFS. This PR will fix the standard GNUMake file, which isn't used in the CIME build but it is currently used by the HAFS build, and it will add a ESMF_VERSION_MAJOR check to the source code. So the PR won't fix everything but it's an improvement.

**Pull request merged**
