### PR TITLE
Bring external land component support to UFS

### PR DESCRIPTION
**Pull request by uturuncoglu**
### Description of changes
This PR aims to extend nems application to support external land component. Along with these changes, the UFS model will be able to support following RTs:
- `datm_cdeps_lnd_gswp3`: 1 day run with CDEPS GSWP3 dataset
- `datm_cdeps_lnd_gswp3_rst`: restart run with CDEPS GSWP3 dataset
- `control_p8_atmlnd_sbs`: side-by-side test with active atmosphere, uses same configuration with `control_p8` and the interaction with FV3 is uni-directional to allow comparing the results coming from FV3/CCPP/NOAHMP with external NOAHMP component

### Specific notes
Contributors other than yourself, if any: No
CMEPS Issues Fixed (include github issue #): 
A minor issue related with the land component which does not provide `cpl_scalars` to mediator is fixed.

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) No 

Any User Interface Changes (namelist or namelist defaults changes)? No

### Testing performed

Testing performed if application target is CESM:
- [x] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines: Cheyenne, Intel MPT
   - details (e.g. failed tests): all tests are passed
- [x] (recommended) CESM testlist_drv.xml
   - machines and compilers: Cheyenne, Intel MPT
   - details (e.g. failed tests): all tests are passed
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [x] (recommended) UFS-coupled testing
   - description: All RTs are run on Cheyenne with Intel and GNU compilers and they are passing.
   - details (e.g. failed tests): No

Testing performed if application target is UFS-HAFS:
- [x] (recommended) UFS-HAFS testing
   - description: All RTs are run on Cheyenne with Intel and GNU compilers and they are passing.
   - details (e.g. failed tests): No

### Hashes used for testing:

- [x] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash: cesm2_3_beta09
- [x] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out: https://github.com/uturuncoglu/ufs-weather-model
  - branch/hash: feature/lnd_noahmp_new (based on hash b5acabf, Sep. 16)
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@mvertens @DeniseWorthen i am currently testing with CESM. I'll update you about it.

**Comment by uturuncoglu** [comment]
all tests are passed without any issue.

**Review by DeniseWorthen — APPROVED** [review]
Sorry for the delay in reviewing. I don't see any issues w/ this PR.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Thanks. I think we will mere this first and update CMEPS in UFS side later with your UFS level PR. Right?

**Comment by DeniseWorthen** [comment]
Yes, my original thought was that your UFS PR will need new baselines for the added tests. But if we did just a CMEPS PR, we would be able to get that one out of the way first, since it will be able to be combined w/ another non-baseline change PR. But at this point there isn't much in the queue. So I'm not sure it is worth it to do them separately.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Then, let's merge this and you just update CMEPS in UFS side. I think it would be easier. @mvertens could you review this PR. Then, we could merge it.

**Comment by uturuncoglu** [comment]
@mvertens I have already run CESM testlist_drv.xml test with cesm2_3_beta09 and they were okay. If you want me to test again. I could do it.

**Comment by mvertens** [comment]
@uturuncoglu - thanks! I should have checked. Please go ahead and merge.

**Pull request merged**
