### PR TITLE
remove multi_driver, add precommit config file

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Multi_driver is always True for cmeps, no need for logic here.  
### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]

**Comment by jedwards4b** [comment]
@fischer-ncar can I merge this before you start beta11 testing?

**Comment by fischer-ncar** [comment]
@jedwards4b Yes you can merge this.  I'm only going to update the cmeps tag to include #329 for beta11 testing.  I want the
testing to go as smooth as possible so I can start the holiday vacation.

**Comment by jedwards4b** [comment]
No we need to merge #327 as well and I think this one should be included too.

**Comment by fischer-ncar** [comment]
Okay, I'll include this pr and #327 in beta11 testing.

**Pull request merged**
