### PR TITLE
fix issue with xgrid reproducibility

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Adds optional flags to ESMF_FieldRegridStore command to make xgrid reproducable.
### Specific notes

Contributors other than yourself, if any: mvertens, esmf team

CMEPS Issues Fixed (include github issue #): 

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [X] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines: cheyenne
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [X] (other) please described in detail
   - machines and compilers cheyenne intel
   - details:  
      The following tests were all rerun on the xgrid and now all PASS
         - ERP_D_Ln9_Vnuopc.f19_f19_mg17.FSD.cheyenne_intel.cam-outfrq9s_sd 
         - ERP_D_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.F2000dev.cheyenne_intel.cam-outfrq9s
         -  ERP_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d
         -  ERP_Ln9_Vnuopc.f09_f09_mg17.2000_CAM60_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV.cheyenne_intel.cam-outfrq9s
Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

**Review by uturuncoglu — APPROVED** [review]
This looks good to me but I just wonder if you need to change also following section of code https://github.com/ESCOMP/CMEPS/blob/22dbf82b123ebfc4136b3f75b1f308e51a90d0d1/mediator/med_phases_aofluxes_mod.F90#L1231 and also https://github.com/ESCOMP/CMEPS/blob/22dbf82b123ebfc4136b3f75b1f308e51a90d0d1/mediator/med_phases_aofluxes_mod.F90#L1240. It would be also nice to test this with UFS and maybe we could get rid of if statements but of course it will take time for me to test those. So, maybe we could aim those in the other PR.

**Comment by jedwards4b** [comment]
@uturuncoglu what additional change are you suggesting?   The tests were rerun with the change that I made and no further changes are required.

**Comment by uturuncoglu** [comment]
@jedwards4b Okay. It is my fault. Those are ESMF_FieldRegrid calls not Store.

**Comment by mvertens** [comment]
@jedwards4b, @uturuncoglu - from a separate email it seems like this change requires a new ESMF tag. Is this correct. If so - this needs to be documented in this PR. Working at other institutions, requirements of new ESMF tags can be challenging.
And if indeed this is the case, this will not be backwards compatible with older ESMF libraries. Please clarify.

**Pull request merged**
