### PR TITLE
new run sequence for B1850 nuopc validation

### PR DESCRIPTION
**Pull request by mvertens**
### Description of changes
new run sequence for B1850 nuopc validation

### Specific notes
This PR requires ESMF https://github.com/esmf-org/esmf/releases/tag/ESMF_8_2_0_beta_snapshot_13 and later snapshots.
With this new snapshot, this PR does the following:
1) Enables a new run RASM_OPTION1 sequence for fully coupled CESM nuopc simulations. 
The new run sequence will look like the following:
```
@432000
@10800
@3600
@1800
  MED med_phases_aofluxes_run
  MED med_phases_prep_ocn_accum
  MED med_phases_ocnalb_run
  MED med_phases_diag_ocn
@@3600
  MED med_phases_prep_ocn_avg
  MED -> OCN :remapMethod=redist
@@
```
With this new run sequence, careful comparison with the RASM_OPTION1 cesm simulation validated this configuration for NUOPC with POP.
2) A fix to the budget table has been put in place to fix problems with MOM6 budgets when running a fully coupled simulation.

**NOTE: prealpha tests need to be run before this PR can be migrated from a draft status.**

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers?
 - [ ] bit for bit
 - [ ] different at roundoff level
 - [x] more substantial - ONLY for B compsets in CESM

Any User Interface Changes (namelist or namelist defaults changes)?
 - [ ] Yes
 - [x] No

Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required):
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [x] (other) please described in detail
   - machines and compilers: cheyenne/intel
   - details (e.g. failed tests): compare new run sequence for B1850 f19_g17 with mct version and verified that new runsequence resolve older problem in validation!

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

Hashes used for testing:
- [x] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - hash: cesm2_3_beta04
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch:
  - hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch:
  - hash:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@DeniseWorthen This PR will make cmeps require ESMF 8.2.0 is that going to be a problem?

**Comment by DeniseWorthen** [comment]
@jedwards4b Let me check on the answer.

**Comment by DeniseWorthen** [comment]
The release notes [here](http://earthsystemmodeling.org/release-schedule/#april-2021---covers-releases-82-83) refer to updating PIO in 8.2/3-- do you know whether that is actually implemented yet in 8.2 ? I ask because we have one configuration which fails with a PIO error and Rocky's/Gerhard's suggestion was that updating PIO from the currrent PIO-2 w/in ESMF might be the solution.

```
fv3.exe            0000000001A7D22A  esmfpio_spmd_util         343  pio_spmd_utils.F90.in
fv3.exe            0000000001A4E834  esmfbox_rearrange         305  box_rearrange.F90.in
fv3.exe            0000000001A07646  esmfrearrange_mp_          80  rearrange.F90.in
```

**Comment by jedwards4b** [comment]
@DeniseWorthen no this work has not been done yet.

**Comment by DeniseWorthen** [comment]
Ok, too bad. 

I don't see that 8.2 is yet released, so I'm assuming you're testing w/ a beta-snapshot. Which snapshot does it need to be at a minimum?

**Comment by rsdunlapiv** [comment]
@DeniseWorthen the latest snapshot is 8.2.0bs14 - https://github.com/esmf-org/esmf/tree/ESMF_8_2_0_beta_snapshot_14

One of the things that @mark-a-potts has done is implemented automated testing of new ESMF snapshots against UFS regression tests (currently just one test, but it needs to be expanded).  The results are posted here:
https://github.com/ufs-community/ufs-test-artifacts/tree/main/hera

At the time of the last ESMF release, UFS had fallen behind quite a bit in the snapshots and this testing was added to make updates more seamless and to find issues early.  @junwang-noaa

**Comment by junwang-noaa** [comment]
Thanks, Rocky. That is a really nice feature. Is the 8.2.0bs14 a stable
version that we can use in UFS?

**Comment by rsdunlapiv** [comment]
@junwang-noaa we know that at least the one automated test is passing (cpld_bmark_wave_v16) and CESM has updated to 8.2.0bs13.  I would recommend running the full RT suite with bs14 and if it passed, updating UFS to the new snapshot.  The important thing is to keep moving along with the snapshots.  ESMF is not a static library and so should be considered an evolving piece like other aspects of the codebase.

**Comment by DeniseWorthen** [comment]
Thanks everyone. I think the next step is as Rocky suggests to test the full RT for 8.2.0bs14. I can ask hpc-stack to install for testing.

**Comment by mvertens** [comment]
@DeniseWorthen @jedwards4b - are you okay with this PR? Can it be merged in that case. We need it for upcoming CESM validation runs.

**Review by jedwards4b — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
I've tested the 8.2.0bs14 for UFS and everything passed; we've got a request in now for this to be built across platforms. It may be a few weeks before we deploy this in UFS so we'll need to delay bringing back any CMEPS updates until then.

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
