### PR TITLE
add werror to extbuild

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Add werror to github testing - no gfortran warnings allowed.

### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 
BFB
Any User Interface Changes (namelist or namelist defaults changes)? NO

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [X] (optional) CESM prealpha test
   - machines and compilers   cheyenne, intel, gnu, github testing.
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [X] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash: cesm2_3_beta11
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

**Comment by jedwards4b** [comment]
I will run cesm prealphas with this + CDEPS https://github.com/ESCOMP/CDEPS/pull/207

**Comment by uturuncoglu** [comment]
@jedwards4b maybe I could test both of them in the same time.

**Comment by jedwards4b** [comment]
Yes - please do!

**Comment by DeniseWorthen** [comment]
@uturuncoglu What testing are you planning? I don't want to replicate anything you were going to do on UFS.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Since i need to test CDEPS PR. I think that could run couple of coupled test but if you want to run the entire RT against this PR please go ahead and I could test CDEPS seperately.

**Comment by DeniseWorthen** [comment]
@uturuncoglu Sure, will do.

**Review by DeniseWorthen — APPROVED** [review]
All UFS tests passed.

**Pull request merged**
